import type { ComposedRules } from '../core/compose.js';
import type { DetectedStack } from '../core/types.js';
import { renderRulesByCategory, stackSummary } from './shared.js';

export function formatCursor(composed: ComposedRules, stack: DetectedStack): string {
  const summary = stackSummary(stack) || 'this project';
  return [
    `---`,
    `description: AI coding rules generated by aiprep for ${summary}`,
    `globs:`,
    `alwaysApply: true`,
    `---`,
    ``,
    `# aiprep — Cursor Rules`,
    ``,
    `Applied presets: ${composed.appliedPresets.join(', ')}.`,
    ``,
    renderRulesByCategory(composed.byCategory),
    ``,
  ].join('\n');
}
