import type { DetectedStack, Rule, RuleCategory } from '../core/types.js';

export const CUSTOM_MARKER = '<!-- Custom rules below this line will be preserved on regeneration -->';

const CATEGORY_TITLES: Record<RuleCategory, string> = {
  architecture: 'Architecture',
  conventions: 'Conventions',
  patterns: 'Patterns',
  imports: 'Imports',
  errors: 'Errors',
  security: 'Security',
  performance: 'Performance',
  testing: 'Testing',
};

export function categoryTitle(c: RuleCategory): string {
  return CATEGORY_TITLES[c];
}

export function stackSummary(stack: DetectedStack): string {
  const parts: string[] = [];
  const runtimes = stack.runtime.filter((r) => r && r !== 'unknown');
  if (runtimes.length) parts.push(runtimes.join(' + '));
  for (const f of stack.frameworks) {
    parts.push(f.version ? `${f.name} ${f.version}` : f.name);
  }
  for (const t of stack.tools) {
    parts.push(t.version ? `${t.name} ${t.version}` : t.name);
  }
  return parts.join(', ');
}

export function renderRulesByCategory(byCategory: Record<RuleCategory, Rule[]>): string {
  const sections: string[] = [];
  for (const cat of Object.keys(byCategory) as RuleCategory[]) {
    const rules = byCategory[cat];
    if (!rules.length) continue;
    sections.push(`### ${categoryTitle(cat)}\n\n${rules.map((r) => `- ${r.content}`).join('\n')}`);
  }
  return sections.join('\n\n');
}

export function renderHeader(agent: string): string {
  return `> Generated by [aiprep](https://github.com/BahaaEldin0/aiprep) — do not edit the generated sections above the marker.
> To regenerate: \`npx aiprep\`
> Target: ${agent}`;
}

export function renderScripts(scripts: Record<string, string>): string {
  const keys = Object.keys(scripts);
  if (!keys.length) return '_No scripts detected._';
  return keys.map((k) => `- \`${k}\` — \`${scripts[k]}\``).join('\n');
}

export function renderStructure(structure: string[]): string {
  if (!structure.length) return '_(structure not captured)_';
  return ['```', ...structure.slice(0, 100), '```'].join('\n');
}

export function appendCustomBlock(content: string, existing: string | null): string {
  const trimmed = content.replace(/\s+$/, '');
  if (!existing) {
    return `${trimmed}\n\n${CUSTOM_MARKER}\n`;
  }
  const idx = existing.indexOf(CUSTOM_MARKER);
  if (idx === -1) return `${trimmed}\n\n${CUSTOM_MARKER}\n`;
  const custom = existing.slice(idx + CUSTOM_MARKER.length).replace(/^\n+/, '');
  if (!custom.trim()) return `${trimmed}\n\n${CUSTOM_MARKER}\n`;
  return `${trimmed}\n\n${CUSTOM_MARKER}\n${custom}`;
}
