import type { ComposedRules } from '../core/compose.js';
import type { DetectedStack } from '../core/types.js';
import { renderRulesByCategory, stackSummary } from './shared.js';

export function formatWindsurf(composed: ComposedRules, stack: DetectedStack): string {
  return [
    `# Windsurf Rules`,
    ``,
    `Generated by aiprep for ${stackSummary(stack) || 'this project'}.`,
    `Presets: ${composed.appliedPresets.join(', ')}.`,
    ``,
    renderRulesByCategory(composed.byCategory),
    ``,
  ].join('\n');
}
